networks:
  jenkins:
    driver: bridge
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:

