version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - kong
      - authelia
    networks:
      - nginx-net
      - kong-net
      - authelia-net

networks:
  nginx-net:
