version: '3.7'

services:
  app-database-sql:
    image: postgres:13
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - app-data-sql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db-net

  app-database-nosql:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - app-data-nosql:/data/db
    ports:
      - 27017:27017
    networks:
      - db-net

volumes:
  app-data-sql:
  app-data-nosql:

networks:
  db-net:
