version: '3.7'

services:
  authelia:
    image: authelia/authelia:latest
    volumes:
      - ./authelia/config:/config
    ports:
      - 9091:9091
    depends_on:
      - redis
    networks:
      - authelia-net

  redis:
    image: redis:alpine
    container_name: authelia-redis
    networks:
      - authelia-net

networks:
  authelia-net:
